### ISSUE TITLE
Cannot use Accelerate framework

### ISSUE THREAD

**Issue by ameensaleem** [kewlbear/Open3D-iOS#1]
After importing
`import Accelerate.vImage`

Cannot use following functions

```
var f32vImageBuffer = vImage_Buffer()
var f16vImageBuffer = vImage_Buffer()

var error = kvImageNoError
```

While trying to use, got out of scope issue

**Comment by kewlbear** [comment]
Is it relevant to this project?

**Comment by 1agora** [comment]
i think it is relevant actually, i am looking into the same issue. 

After embedding Open3D, whatever existing code which is using Accelerate is "out of scope".

Numpy has `linkerSettings: [.linkedFramework("Accelerate")]`

**Comment by kewlbear** [comment]
@1agora Have you seen this? https://stackoverflow.com/a/58525429/2570853

**Comment by 1agora** [comment]
@kewlbear i can't see how this post is related, but it helped me with another issue i had, thanks! 
seems like a linker config issue where accelerate framework being lost in the imports

@ameensaleem did you figure it out? if you did please share)

**Comment by ameensaleem** [comment]
@1agora I'm still looking for fix, Previously I thought the issue is with LAPACKE-iOS, 
https://github.com/kewlbear/LAPACKE-iOS/tree/main/Sources/Accelerate

after you've mentioned I'm looking Numpy and try to fix this, I'll share if I did.

**Comment by kewlbear** [comment]
@ameensaleem You were right. LAPACKE-iOS had name clash problem. I pushed fixes to the repo. Please see if your problem is fixed. Thanks!

**Comment by ameensaleem** [comment]
@kewlbear Now I can access Accelerate Framework, Thank you so much!.
