### ISSUE TITLE
Using Open3D-iOS in a swift package

### ISSUE THREAD

**Issue by acamill** [kewlbear/Open3D-iOS#12]
Anyeonghaseyo, I'm trying to use this as a dependency in a SPM package

But It's not working in the parent project, err being `error: missing required module 'LinkPython'`

I think it's due to the fact that package have this error related to Umbrella. 
![Screenshot 2021-04-13 at 12 06 40](https://user-images.githubusercontent.com/40299747/114495476-b7ce4f00-9c50-11eb-8241-8ca1e957f20d.png)

I think for now I'll just add the dependency to the project directly, but I wanted to split thing for code reuse. I'm not savy enough with packages to fix it.

Cheers and thanks again for this

```
let package = Package(
    name: "PointCloudProcessor",
    products: [
        // Products define the executables and libraries a package produces, and make them visible to other packages.
        .library(
            name: "PointCloudProcessor",
            targets: ["PointCloudProcessor"]),
    ],
    dependencies: [
        // Dependencies declare other packages that this package depends on.
        // .package(url: /* package url */, from: "1.0.0"),
        .package(url: "https://github.com/kewlbear/Open3D-iOS.git", .branch("main")),
        .package(url: "https://github.com/kewlbear/PythonKit.git", .branch("master"))
    ],
    targets: [
        // Targets are the basic building blocks of a package. A target can define a module or a test suite.
        // Targets can depend on other targets in this package, and on products in packages this package depends on.
        .target(
            name: "PointCloudProcessor",
            dependencies: ["PythonKit", "Open3D-iOS"]),
        .testTarget(
            name: "PointCloudProcessorTests",
            dependencies: ["PointCloudProcessor"]),
    ]
)
```

**Comment by kewlbear** [comment]
You can ignore umbrella warning.  Have you updated Python-iOS package to latest revision?  I've seen the same error and pushed a fix already.

**Comment by acamill** [comment]
oh, no I'll give it a go

**Comment by acamill** [comment]
The PythonIOS I have to include to my dependencies or it's part of PythonKit?

**Comment by acamill** [comment]
Ok seems it was some missing dependencies declaration. Working now

**Comment by 1agora** [comment]
> @acamill what dependancies were missing for you?
