### ISSUE TITLE
occur error when i archive ipa file

### ISSUE THREAD

**Issue by wxyz-lang** [kewlbear/Open3D-iOS#14]
![image](https://user-images.githubusercontent.com/18107059/119868054-23deeb00-bf51-11eb-95a8-1a3373f1ab65.png)

![image](https://user-images.githubusercontent.com/18107059/119868108-38bb7e80-bf51-11eb-81ad-270c9decc5d6.png)

![image](https://user-images.githubusercontent.com/18107059/119868133-41ac5000-bf51-11eb-8694-df3ee77fc22f.png)

![image](https://user-images.githubusercontent.com/18107059/119868172-4cff7b80-bf51-11eb-840c-b5018e5b3853.png)

**Comment by wxyz-lang** [comment]
my xcode version is 12.4, these error may be caused the xcode version

https://stackoverflow.com/questions/61673776/invalid-bundle-structure-the-binary-file-is-not-permitted-in-xcode-11-when-uploa

**Comment by kewlbear** [comment]
You should update to Xcode 12.5. See #11.

**Comment by wxyz-lang** [comment]
Thanks very much, i have solve this problem.
