### ISSUE TITLE
Mac Catalyst support OR Ignore in Mac Catalyst

### ISSUE THREAD

**Issue by PrashantKT** [kewlbear/Open3D-iOS#16]
Hi Thanks for this awesome library for iOS 

my app has Mac catalyst support as well so I am not able to compile for Mac catalyst 

is there any way to ignore this framework files for that 

What I have tried is manually Like this and make framework iOS only in general build setting tab 

but NumPy-iOS sdk has also some framework , 

Could you please guide me how to fix this . 

how you make this library working for iOS , is there any tutorial or something I can learn 

<img width="530" alt="Screenshot 2021-06-15 at 8 24 06 PM" src="https://user-images.githubusercontent.com/35359315/122075366-a6075480-ce17-11eb-90ec-c1e4d231e7c3.png">

**Comment by kewlbear** [comment]
How about changing "Platforms" to "iOS" in target's "General" or "Build Phases"?
