### ISSUE TITLE
cannot read images

### ISSUE THREAD

**Issue by yanyan-li** [kewlbear/Open3D-iOS#17]
Hi, kewlbear, I am new to iOS development. Thank you for your great work. 
Currently, we use this package to do 3D reconstruction, which can be compiled successfully but will affect other steps, for example, we cannot save rgbd images from opencv. Very wired. BTW, what is the version of this package? I want to check whether there are any new changes.  
           
            std::string rgb_file_name = "path_rgb.png";
            std::string depth_file_name = "path_depth.png";
            open3d::geometry::Image o_depth, o_color;

            bool  bColor = open3d::io::ReadImage(rgb_file_name, o_color);
            bool  bDepth = open3d::io::ReadImage(depth_file_name, o_depth);
            
            // merge rgb amd depth images into rgbd
            auto rgbd = open3d::geometry::RGBDImage(o_color, o_depth);
            
            open3d::camera::PinholeCameraIntrinsic intrisic_ (o_color.width_, o_color.height_, fx, fy, cx, cy);
            
            volume.Integrate(rgbd, intrisic_, extrinsic);

**Comment by kewlbear** [comment]
As you can see at https://github.com/kewlbear/Open3D, It is built from v0.12.0.  

Can you provide a minimal project to reproduce the problem?  In your code snippet above, where the problem occurs?  Any error message/code for the problem?

**Comment by yanyan-li** [comment]
Hi, thanks for your reply. I want to use _open3d Image_ to read rgb and depth maps from my iPhone memory.  It seems that the following lines cannot do that, even there are no errors in the compiling process.

open3d::io::ReadImage(rgb_file_name, o_color);  
open3d::io::ReadImagePNG(rgb_file_name, o_color);  

Do you have any suggestions for reading images?

**Comment by kewlbear** [comment]
Does ReadImage() return true, meaning success?
Where did the file come from?
