### ISSUE TITLE
filling hole in trianglemesh & crashed

### ISSUE THREAD

**Issue by LiuKaoji** [kewlbear/Open3D-iOS#19]
Hi, kewlbear, I am new to use open3d on iOS device. Thanks for the o3d swift package of you。
I need  use this package to edit triangle mesh, but this repository does not include some important functions, for example, TriangleMeshHoleFill.cpp. I have imported this file to the project ，and sometimes crashed in HalfEdgeTriangleMesh::CreateFromTriangleMesh.hope u could share me some ideas to continue my work. 

<img width="424" alt="图片" src="https://user-images.githubusercontent.com/47659827/127082938-be7afb7d-62d8-4428-855e-05c3abb1a285.png">

https://user-images.githubusercontent.com/47659827/127083364-d6656e3b-4a8d-43aa-8705-67d51b873c49.MP4

TriangleMeshHoleFill.cpp
https://github.com/kongsgard/Open3D/blob/initial-patching/cpp/open3d/geometry/TriangleMeshHoleFill.cpp

**Comment by kewlbear** [comment]
Maybe relavant: https://stackoverflow.com/a/65352381/2570853

You better ask elsewhere.

**Comment by LiuKaoji** [comment]
> Maybe relavant: https://stackoverflow.com/a/65352381/2570853
> 
> You better ask elsewhere.

Thanks for your Idea. I'll try anoter way
