### ISSUE TITLE
Archive size too big

### ISSUE THREAD

**Issue by 1agora** [kewlbear/Open3D-iOS#2]
After implementing in existing project, the size of the app archive is over 1G (libassimp.a = 927Mb)
is there a way to make it lighter? as it's not AppStore friendly at all.
Any help greatly appreciated.

**Comment by 1agora** [comment]
thanks for you effort! i believe it worked initially, but latest build generates the following error(s) when built using EnableBitcode: Yes : 

`/libcrypto.a(a_object.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by kewlbear** [comment]
Updated Python-iOS package with fix. Please update the package to see if the issue is resolved.

**Comment by acamill** [comment]
@kewlbear  Thanks you for these update
