### ISSUE TITLE
Open3D v0.13

### ISSUE THREAD

**Issue by 1agora** [kewlbear/Open3D-iOS#21]
is it possible for iOS?

**Comment by HeoJinLareine** [comment]
> is it possible for iOS?

Hi, did you figurred out how to do reconstruction??

**Comment by kewlbear** [comment]
Have you tried building using my patches and scripts?

**Comment by 1agora** [comment]
> Have you tried building using my patches and scripts?

not yet, i need more courage for that :)

**Comment by kewlbear** [comment]
Done!
