### ISSUE TITLE
How to look closely inside package for parameters?

### ISSUE THREAD

**Issue by HeoJinLareine** [kewlbear/Open3D-iOS#23]
I've reconstructed with create_from_point_cloud_poisson method.
But, in Open3d python frameworks, 
static create_from_point_cloud_poisson(pcd, depth=8, width=0, scale=1.1, linear_fit=False, n_threads=- 1)
It takes 6 arguments, but I wasn't able to figure out how to apply own parameter on Open3d-iOS.
Is there any way to figure this out?

**Comment by kewlbear** [comment]
I think you can do something like:
```
o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth: 8, width: 0, scale: 1.1, linear_fit: False, n_threads: - 1)
```

**Comment by kewlbear** [comment]
See https://github.com/tensorflow/swift/blob/main/docs/PythonInteroperability.md#dynamically-callable-types.

**Comment by HeoJinLareine** [comment]
> See https://github.com/tensorflow/swift/blob/main/docs/PythonInteroperability.md#dynamically-callable-types.

I've tried this, but the error keep comes up.
Open3D_Test was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by HeoJinLareine** [comment]
Thanks, it worked correctly !

**Comment by HeoJinLareine** [comment]
o3d.geometry.TriangleMesh.create_from_point_cloud_poisson(pcd, depth: 8, width: 0, scale: 1.1, linear_fit: False, n_threads: - 1) -> works fine!
