### ISSUE TITLE
Importing Open3D-iOS on Xcode 13.

### ISSUE THREAD

**Issue by HeoJinLareine** [kewlbear/Open3D-iOS#24]
It does work on Xcode 12, but when trying to import package on xcode 13, It doesn't work.

Is there any way to solve this problem?

**Comment by kewlbear** [comment]
Any error message? Steps to reproduce?

**Comment by eugene-kotyashov** [comment]
I think in Usage section 
Open3DSupport.sitePackageUrl.insertPythonPath()
NumPySupport.sitePackageUrl.insertPythonPath()
has to be changed to 
Open3DSupport.sitePackagesUrl.insertPythonPath()
NumPySupport.sitePackagesUrl.insertPythonPath()
