### ISSUE TITLE
No module named 'open3d.cpu.pybind'

### ISSUE THREAD

**Issue by manhvuvan281** [kewlbear/Open3D-iOS#27]
clang-1300.0.29.3
x86_64-apple-darwin20.6.0
Mac Intel
I think the update version of Python-iOS (3.9) has some problem with Open3D-iOS.

**Comment by HeoJinLareine** [comment]
> clang-1300.0.29.3
> x86_64-apple-darwin20.6.0
> Mac Intel
> I think the update version of Python-iOS (3.9) has some problem with Open3D-iOS.

Same Problem here. Did you featured out how to solve this problem?

**Comment by manhvuvan281** [comment]
@HeoJinLareine 
I forked his'dependencies, and edited Python version to 3.8.2.
https://github.com/manhvuvan281/Open3D-iOS

**Comment by manhvuvan281** [comment]
@kewlbear  fixed!

**Comment by darktakayanagi** [comment]
@manhvuvan281 how did you fix it?
I'm still having that error on my end

**Comment by kewlbear** [comment]
Thanks for reporting!  Just fixed it.  Please update the package from Project navigator > Package dependencies.

**Comment by manhvuvan281** [comment]
---- Completely remove ----
Xcode > File > Add Package > (Choose package->Option->Remove package)
Project navigator > Package dependencies > Remove open3d-ios/PythonKit
Product > Clean build Folder > Close project.
---- Add package again---
Open project > Add Package
