### ISSUE TITLE
OpenCV-ios를 구성해보고 싶습니다.

### ISSUE THREAD

**Issue by eunwonki** [kewlbear/Open3D-iOS#30]
안녕하세요. 한국에 거주하시는 것같아 한국말로 글 남깁니다.

@kewlbear 개발자님께서 구성해주신 몇 가지 저장소를 확인해보고,
그 중 [Open3D-ios](https://github.com/kewlbear/Open3D-iOS)라는 것을 
처음 써보고 굉장히 놀랐습니다. PythonKit이라던지, ios에서 파이썬 코드를 쓰게 구성하신 것을 처음 봐서요...

kivy-ios: https://github.com/kewlbear/kivy-ios

Numpy-ios: https://github.com/kewlbear/NumPy-iOS
Open3D-ios: https://github.com/kewlbear/Open3D-iOS

더 나아가 OpenCV-ios나 여유가 있다면, 다른 머신러닝 관련 라이브러리도 이런게 있으면 편할거 같단 생각이 들어서 구성해보고 싶은데,
Repository가 많기도 해보이고, 제가 아직 초보개발자라 구성만 보고는 구조가 쉽게 파악되지는 않아서요.

쓰고 싶은 라이브러리가 ios에서 실행가능한 binary 파일이 존재하면 모두 ios에서 파이썬 코드로 사용 가능하도록 구성이 가능한건가요?
그리고 어떤 파일이나 구성들이 필수적으로 필요한건지 알 수 있을까요???

**Comment by kewlbear** [comment]
안녕하세요?
OpenCV의 경우 C/C++로 사용하시면 다른 사람이 빌드한 라이브러리를 링크해주시면 됩니다.
혹시 파이썬이 더 편하시면 파이썬 코드를 앱에 포함시키고 PythonKit을 통해 실행하시면 될 듯 합니다.
안된다면 kivy-ios에 opencv recipe가 있으면 그걸로 빌드하면 됩니다.
