### ISSUE TITLE
Is there anyway read or use jpg/png image in open3d ios?

### ISSUE THREAD

**Issue by HeoJinLareine** [kewlbear/Open3D-iOS#35]
I've saved image by..

    func saveJpg(image: UIImage, name: String) {
        if let jpgData = image.jpegData(compressionQuality: 1.0),
            let path = documentDirectoryPath()?.appendingPathComponent("\(name).jpg") {
                rgbPaths.append(path.absoluteString)
            try? jpgData.write(to: path)
        }
    }

and with path, I tried to read read image with ..
o3d.io.read_image(rgbPath)
which shows ..
[1;33m[Open3D WARNING] Read PNG failed: unable to parse header.[0;m

How can I read image in open3d ios?

**Comment by kewlbear** [comment]
Change
```
rgbPaths.append(path.absoluteString)
```
to
```
rgbPaths.append(path.path)
```

**Comment by HeoJinLareine** [comment]
Thanks, but now it saids [ Unsupported image format. ]
I guess jpgData is 16bit image, but open3d only get 8bit. 
Is there was way to solve this?

**Comment by kewlbear** [comment]
My test app reads the file successfully. How about checking the file using your Mac?
