### ISSUE TITLE
How you have build this 

### ISSUE THREAD

**Issue by PrashantKT** [kewlbear/Open3D-iOS#36]
Sir  I have a question how you have build this 

as it has python so I am curious how to build this  if you guide me I will really appreciate it 

Thanks in advance

**Comment by kewlbear** [comment]
You can follow the steps in this script: https://github.com/kewlbear/Open3D-iOS/blob/8d31a49038f273e5b0292b4ae4320f3f343ae554/Scripts/toolchain.sh.

Python is embedded into apps.  Kivy-iOS was used to build Python for iOS.

**Comment by raju535482** [comment]
@kewlbear Can you please help in building Open3D 0.14.0 or 0.15.0 for Android arm64-v8a abi?

**Comment by 100YardDasher** [comment]
@kewlbear I got this error when running the script. Where should I get that project file?

`xcodebuild: error: 'build/Open3D.xcodeproj' does not exist.`

**Comment by kewlbear** [comment]
@raju535482 Sorry, I'm not interested.
