### ISSUE TITLE
Same for Android

### ISSUE THREAD

**Issue by lookquad** [kewlbear/Open3D-iOS#4]
Hi thank you for this. Any reference where I can find the same for android with a sample open3d application. It would be a great help. Sorry for asking in issues but I really need one.

**Comment by kewlbear** [comment]
I think it's possible for anyone with NDK experience by doing similar things I've done in https://github.com/kewlbear/Open3D. But I have only basic Android/NDK development experience. So if I do it, it will take months at least.
