### ISSUE TITLE
Eigen headers are not exposed when trying to use C++ based Open3d from Obj-C++ code

### ISSUE THREAD

**Issue by pzoltowski** [kewlbear/Open3D-iOS#40]
I'm current using this swift/python based package but want to port some code to use Open3d C++ based code directly from Obj-c++ code. 

I included:
`
#import <open3d/Open3D.h>
`
but I'm getting compiler error
`
#include <Eigen/Core>                                   'Eigen/Core' file not found
`
from:
open3d PinholeCameraIntrinsic.h

Is there a way to expose Eigen headers from this Open3d-iOS package so that we can still directly call C++ based code?
When I'm embedding another copy of Eigen project to my project Eigen has to be called as user defined headers I guess and Open3d won't see it.
#include "Eigen/Core"

**Comment by kewlbear** [comment]
Did you check out #15?
