### ISSUE TITLE
Cannot Use open3d.visualization

### ISSUE THREAD

**Issue by yinhaosen** [kewlbear/Open3D-iOS#44]
There seems no Open3D visualization module provided in this project. Any way to implement a point cloud visualizer in IOS?

**Comment by kewlbear** [comment]
Open3D uses OpenGL for visualization and iOS doesn't support it.  You can use OpenGL ES, Metal or SceneKit for visualization.  See my example app for SceneKit integration.

**Comment by yinhaosen** [comment]
For SceneKit, is it possible to implement a free-view camera (zoom in/out, translation) to observe point cloud because your example app seems it only can do rotation with a fixed-view camera.

**Comment by kewlbear** [comment]
Of course.  See https://developer.apple.com/documentation/scenekit/scncamera.
