### ISSUE TITLE
Assertion failed: (NPY_CHECK_GIL_HELD())

### ISSUE THREAD

**Issue by punkoffice** [kewlbear/Open3D-iOS#9]
I'm trying to use Numpy in a background thread but I get the assertion failure.

I'm testing using this command:
`print(np.asarray([[1,2,3],[3,4,5]]))`

I'm not sure how to do the setup for background thread with these commands:
                        `PythonSupport.initialize()`
                        `Open3DSupport.sitePackagesURL.insertPythonPath()`
                        `NumPySupport.sitePackagesURL.insertPythonPath()`

If I call on the main thread then np commands won't work.  If I call in the background thread then it works first time only.  

Can someone tell me the best way to use Python/open3D in a background thread?

**Comment by kewlbear** [comment]
I've updated example app and Python-iOS package (a dependency of Open3D-iOS) to show a way of achieving your goal.

**Comment by punkoffice** [comment]
> I've updated example app and Python-iOS package (a dependency of Open3D-iOS) to show a way of achieving your goal.

This works for my app.  Thank you!
